### PR TITLE
Fix compilation issues on zig  0.12.0-dev.2150+63de8a598

### PR DESCRIPTION
**Pull request by melhindi**
Hi @elerch,
I want to use the aws-sdk-for-zig for a project that I am developing on zig master.
These where the changes required to compile on 0.12.0-dev.2150+63de8a598.
While the code compiles, for some reason I have not investigated yet, the tests get stuck at step `[6/21] zig test Debug riscv64-linux... LLVM Emit Object...`

As I cannot open a PR on your self-hosted Gitea instance, I am opening this PR on the github mirror repository.
Happy to contribute also in future if you accept PRs.

### CODE REVIEW

**Comment by melhindi** [comment]
compatibility with 0.11 is a valid concern, however, as you can see in the current PR the required changes are significant and I am not sure if comptime switches are the best way to go.
How about two different branches or just a tag if you do not want to add any additional features/improvements for 0.11?

**Comment by elerch** [comment]
Sure, I could maintain a 0.12 branch. Some of the changes (e.g. var->const) in your PR could apply just fine to 0.11 as well.

**Comment by melhindi** [comment]
true, should I go ahead and separate them out?

**Comment by elerch** [comment]
That would be great, yes - thanks

**Comment by melhindi** [comment]
I created PR #2 with the const changes. 
Happy to modify this PR (or close it and create a new one) once you create the 0.12 branch

**Comment by elerch** [comment]
This is the approach I've come up with:

`master` will track 0.11, with the idea of continuing to upgrade to latest released zig (0.11.1 when released, 0.12 when released, etc)

`zig-develop` branch will track unreleased zig. I've been down this road in the past and...it's tricky. So to try to keep track, I set up two GitHub actions. One of the actions will simply download latest zig master every night and compile with it. That's effectively a canary, but it will also trigger on push to any `zig-develop*` branch, so that will allow iteration. The second action will track to the latest mach engine nominated zig version. That will provide some medium term stability guarantees.

I created the `zig-develop` branch and associated Gitea (and GitHub) actions. If you can move this PR over to that branch, that would be helpful. I did notice you did a once-over on `src/http_client_17015_issue.zig`, but that's not actually necessary. That issue is addressed by the [PR I provided to the zig stdlib](https://github.com/ziglang/zig/pull/17235), so we should be able to delete the file and set the `raw_uri` option to ignore any modification of the url. One of the unit tests was set up to check this, so as long as it passes all the tests it should be fine.

**Comment by melhindi** [comment]
sounds good to me :)
I'll move the PR to the other branch.
Yes, I noticed that `src/http_client_17015_issue.zig` is obsolete and I already tested removing it locally.
My plan was to delete it and also the workaround for https://github.com/ziglang/zig/issues/15626 in a separate PR

**Comment by elerch** [comment]
@melhindi - fyi I would like to get the `zig-develop` branch building this weekend on the mach [2024.03 nominated zig version](https://github.com/hexops/mach/issues/1147#issuecomment-1986585543). If you have a chance to get me any patches/new PR I'm happy to take them, otherwise I'll leverage this PR as a starting point. My goal is to have master branch on 0.12 pretty close to release of 0.12. Zig 0.12 appears imminent, but they have already pushed out twice, so anything can happen

**Comment by elerch** [comment]
Thanks for the help, this was a useful guide! I'm closing this PR. The [zig-develop](https://github.com/elerch/aws-sdk-for-zig/tree/zig-develop) branch builds and tests fine with [2024.3.0-mach](https://machengine.org/about/nominated-zig/#nominated-zig-history). The example and codegen works as well. I'm seeing failures on GitHub actions, but my own server is now green so it's clearly a CI problem I will tackle later.

Note that nightly is still broken - there have been a couple breaking changes in the last few weeks. Also, LLVM regression has bitten one test for Windows x86_64 and slowed compile times dramatically for riscv64-linux - these two issues are now highlighted in the readme on the zig-develop branch.

**Comment by elerch** [comment]
Looks like GHA failure is due to the runner trying to execute the windows test executable. Will handle that later - badges on the zig-develop readme utilize my home CI server and reflect accurate status.

**Pull request closed without merging**
